
name: 'Test'

on:
  push:
    branches:
      - main
  pull_request:

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: "Test"
        uses: ./
        with:
          api-key: ${{ secrets.ENHANCEDOCS_API_KEY }}

      - run: env
